### ISSUE TITLE
Add a default empty companion for extension

### ISSUE THREAD

**Issue by mohsin-sq** [pwall567/json-kotlin-schema-codegen#19]
It would be helpful if you provided a default `companion object {}` to the generated classes so that we could write static extension methods (like various constructors or some converters, etc..).

**Comment by pwall567** [comment]
Hi – I like that idea!  I encourage people to use extension functions on the generated classes, and this is a further development of the same concept.

I see a couple of problems, however.  I like the idea of the generated code being as simple as possible, and I am reluctant to add anything that would lead to more "clutter" that might confuse some users.  Also, companion objects cause a class file to be generated, and even if this is invisible under normal circumstances, I don't like the idea of causing unnecessary inefficiency.

That means I would probably make it an optional feature, which could be selected either for the entire run of the generator or for specified classes.

Let me think about that – I'll get back to you shortly.  And thanks for the suggestion!

**Comment by pwall567** [comment]
It turned out to be reasonably easy to implement – try version 0.86 (uploaded a short while ago).

I made it subject to a configuration option – see the [companionObject](https://github.com/pwall567/json-kotlin-schema-codegen/blob/main/CONFIG.md#companionobject) section of the Configuration Guide.  Let me know if this works OK for you.

Thanks again for the suggestion – this is something I will certainly make use of in my own uses of the generator.

**Comment by mohsin-sq** [comment]
Hi Peter,

Thanks for such a fast turnaround!

It makes great sense to make it a configuration option and will certainly work for me. Plan on shortly bumping our version and using the feature. Thanks again!

Best,
Mohsin

**Comment by pwall567** [comment]
I'm closing this issue as resolved.  If you think there are still outstanding questions, feel free to reopen it or create a new issue.
