### ISSUE TITLE
Wrong classpath for templates

### ISSUE THREAD

**Issue by hoeller** [pwall567/json-kotlin-schema-codegen#48]
I have an issue with the new version 0.110

I am parsing a json template to generate a kotlin class which was successful with version 0.109. With the latest version I get this error message:

`Caused by: io.kjson.mustache.parser.MustacheParserException: Can't locate template - class`

This is because the mustache parser cannot resolve the standard template for a kotlin class. The exception is thrown here:

https://github.com/pwall567/mustache-k/blob/7094aab35300d27d42915b851a5bb1dfe9504dab/src/main/kotlin/io/kjson/mustache/parser/Parser.kt#L238
```kotlin
        for (directory in directories) {
            try {
                return directory.resolve(name).load()
            }
            catch (_: ResourceNotFoundException) { // do nothing
            }
        }
        throw MustacheParserException("Can't locate template - $name")
```
By debugging I can see that `directories` contains two locations:

```
jar:file:/Users/hoeller/.gradle/caches/modules-2/files-2.1/net.pwall.json/json-kotlin-schema-codegen/0.110/96f296b26a03b82b32c0a9cb94cad74b25bfd2ce/json-kotlin-schema-codegen-0.110.jar!/common/
jar:file:/Users/hoeller/.gradle/wrapper/dists/gradle-8.4-all/byeatq2t0fhfi576avs1x0p6d/gradle-8.4/lib/kotlin-stdlib-1.9.10.jar!/kotlin/
```

I assume that the kotlin-stdlib shouldn't be here because the templates obviously must be retrieved from the classpath of *this* library:

```
json-kotlin-schema-codegen-0.110.jar/common
json-kotlin-schema-codegen-0.110.jar/kotlin (this contains class.mustache)
```

These `directories` above are assigned as a default value in `CodeGenerator.kt`. This is in fact a change from 0.109 to 0.110.

https://github.com/pwall567/json-kotlin-schema-codegen/compare/0.109...0.110#diff-769df6384b59617c2652aefaefa3dc16d5d880b765fb2eb8c3ae75a658140bdeR167
```kotlin
    var templateParser: MustacheParser by DefaultValue {
        MustacheParser().apply {
            for (directory in targetLanguage.directories) {
                val url = Resource.classPathURL("/$directory/") ?: fatal("Can't locate template directory /$directory")
                addDirectory(url)
            }
        }
    }
```

Somehow the directory `common` is appended to the classpath of the codegen lib but the `kotlin` directory is appended to the classpath of the kotlin-stdlib?? It is only by accident that this does not throw an exception, because all kotlin-stdlib packages start with `kotlin` lol. 

Is this a configuration issue in my project? Or how does it determine the wrong classpath?

**Comment by pwall567** [comment]
Hi @hoeller, thanks for your very helpful information gathering on this issue.  One of the changes in version 0.110 was a switch to a new template loader, which required the template locations to be specified in a different manner.  Unfortunately, the fact that one of the directories was named `kotlin` caused confusion with the class directory in the standard library, also named `kotlin`, but this didn't show up in my tests.

I have now moved all the template directories under a high level `templates` directory (where arguably they should have been all along), so that now the `kotlin` directory becomes `templates/kotlin` which should eliminate the confusion.

Thanks again for your help in tracking this down; try version 0.111 which should fix the problem.

-Peter Wall

**Comment by hoeller** [comment]
Hi Peter, thank you very much for the quick reaction. With 0.111 the problem is fixed for my project, great! Thanks for your work - Paul
